<?xml version="1.0" ?>
<robot name="warebot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find warebot_2020_description)/urdf/material.xacro"/>
  <xacro:include filename="$(find warebot_2020_description)/urdf/warebot.gazebo.xacro"/>

  <xacro:property name="asus_cam_rgb_px" value="0.005"/>
  <xacro:property name="asus_cam_rgb_py" value="0.018"/>
  <xacro:property name="asus_cam_rgb_pz" value="0.013"/>
  <xacro:property name="asus_cam_depth_offset" value="0.01"/>

  <!--World link as base foot used for fixing robot to Gazebo-->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <!--4 wheel robot-->
  <!--
  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Chassis.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="60"/>
      <inertia ixx="1.215" ixy="0.0" ixz="0.0"
               iyy="1.215" iyz="0.0"
               izz="2.075" />
    </inertial>
  </link>

  <joint name="wheel_left_front_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_front_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_front_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_front_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_front_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_front_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 3.14"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_rear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_right_rear_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="wheel_right_rear_joint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 3.14"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
    </inertial>
  </link>

  <joint name="wheel_left_rear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_left_rear_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="wheel_left_rear_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 3.14"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>
  -->

  <!--2 wheel robot with castor wheels-->
  <link name="base_link">
    <inertial>
      <mass value="60"/>
        <origin rpy="0 0 0" xyz="0 0 0.1"/>
        <!-- x=0.5 y=0.5 z=0.207-->
        <inertia ixx="1.215" ixy="0.0" ixz="0.0" iyy="1.215" iyz="0.0" izz="2.075"/>
    </inertial>

    <collision name="chassis_collision">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Chassis.stl" scale="0.01 0.01 0.01"/>
      </geometry>
    </collision>

    <collision name="caster_collision_back">
      <origin rpy="0 0 0" xyz="-0.24 0 -0.074"/>
      <geometry>
        <sphere radius="0.04"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <collision name="caster_collision_front">
      <origin rpy="0 0 0" xyz="0.24 0 -0.074"/>
      <geometry>
        <sphere radius="0.04"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name="chassis_visual">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Chassis.stl" scale="0.01 0.01 0.01"/>
      </geometry>
    </visual>

    <visual name="caster_visual_back">
      <origin rpy="0 0 0" xyz="-0.24 0 -0.06"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/WareBot_Caster.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </visual>

    <visual name="caster_visual_front">
      <origin rpy="0 0 -3.14158" xyz="0.24 0 -0.04"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/WareBot_Caster.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </visual>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin rpy="0 0 0" xyz="0.009 0.27 -0.0308"/>
    <axis xyz="0 1 0"/>
    <limit effort="90" velocity="20"/>
  </joint>

  <link name="wheel_left_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <!-- x=0.165 y=0.05 z=0.165-->
      <inertia ixx="0.0123" ixy="0" ixz="0" iyy="0.0226" iyz="0" izz="0.0123"/>
    </inertial>

    <collision name="wheel_left_collision">
      <origin rpy="1.5707 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.0835"/>
        </geometry>
    </collision>

    <visual name="wheel_left_visual">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://warebot_2020_description/meshes/WareBot_Wheel.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </visual>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin rpy="0 0 0" xyz="-0.009 -0.27 -0.0308"/>
    <axis xyz="0 1 0"/>
    <limit effort="90" velocity="20"/>
  </joint>

  <link name="wheel_right_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0123" ixy="0" ixz="0" iyy="0.0226" iyz="0" izz="0.0123"/>
    </inertial>

    <collision name="warebot_wheel_right_collision">
      <origin rpy="1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.0835"/>
      </geometry>
    </collision>

    <visual name="warebot_wheel_right_visual">
      <origin rpy="0 0 3.14" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/WareBot_Wheel.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </visual>
  </link>

  <!--
  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>
  -->

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>
  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.064 -0.065 0.094" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://turtlebot3_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${asus_cam_rgb_px} ${asus_cam_rgb_py} ${asus_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${asus_cam_rgb_px} ${asus_cam_rgb_py + asus_cam_depth_offset} ${asus_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>
