<?xml version="1.0" ?>
<robot name="warebot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find warebot_2020_description)/urdf/material.xacro"/>
  <xacro:include filename="$(find warebot_2020_description)/urdf/warebot.gazebo.xacro"/>

  <xacro:property name="asus_cam_rgb_px" value="0.005"/>
  <xacro:property name="asus_cam_rgb_py" value="0.018"/>
  <xacro:property name="asus_cam_rgb_pz" value="0.013"/>
  <xacro:property name="asus_cam_depth_offset" value="0.01"/>

  <!--World link as base foot used for fixing robot to Gazebo-->
  <link name="base_footprint"></link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <!--4 wheel robot-->
  <link name="base_link">
    <inertial>
      <mass value="60"/>
        <origin rpy="0 0 0" xyz="0 0 0.1"/>
        <!-- x=0.5 y=0.5 z=0.207-->
        <inertia ixx="1.215" ixy="0.0" ixz="0.0" 
                 iyy="1.215" iyz="0.0" 
                 izz="2.075"/>
    </inertial>

    <collision name="chassis_collision">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Chassis.dae" scale="1.0 1.0 1.0"/>
      </geometry>
    </collision>

    <visual name="chassis_visual">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Chassis.dae" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="light_black"/>
    </visual>
  </link>

  <joint name="left_front_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_front_link"/>
    <origin rpy="0 0 0" xyz="0.06 0.27 -0.1"/>
    <axis xyz="0 1 0"/>
    <limit effort="90" velocity="20"/>
  </joint>

  <link name="wheel_left_front_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <!-- x=0.165 y=0.05 z=0.165-->
      <inertia ixx="0.0123" ixy="0" ixz="0" 
               iyy="0.0226" iyz="0" 
               izz="0.0123"/>
    </inertial>

    <collision name="wheel_left_front_collision">
      <origin rpy="1.5707 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.0835"/>
        </geometry>
    </collision>

    <visual name="wheel_left_front_visual">
      <origin rpy="0 0 3.14" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://warebot_2020_description/meshes/Wheel.dae" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="right_front_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_front_link"/>
    <origin rpy="0 0 0" xyz="0.06 -0.285 -0.1"/>
    <axis xyz="0 1 0"/>
    <limit effort="90" velocity="20"/>
  </joint>

  <link name="wheel_right_front_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0123" ixy="0" ixz="0" 
               iyy="0.0226" iyz="0" 
               izz="0.0123"/>
    </inertial>

    <collision name="wheel_right_front_collision">
      <origin rpy="1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.0835"/>
      </geometry>
    </collision>

    <visual name="wheel_right_front_visual">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Wheel.dae" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="left_rear_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_rear_link"/>
    <origin rpy="0 0 0" xyz="-0.2 0.27 -0.1"/>
    <axis xyz="0 1 0"/>
    <limit effort="90" velocity="20"/>
  </joint>

  <link name="wheel_left_rear_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <!-- x=0.165 y=0.05 z=0.165-->
      <inertia ixx="0.0123" ixy="0" ixz="0" 
               iyy="0.0226" iyz="0" 
               izz="0.0123"/>
    </inertial>

    <collision name="wheel_left_rear_collision">
      <origin rpy="1.5707 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.05" radius="0.0835"/>
        </geometry>
    </collision>

    <visual name="wheel_left_front_visual">
      <origin rpy="0 0 3.14" xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://warebot_2020_description/meshes/Wheel.dae" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="right_rear_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_rear_link"/>
    <origin rpy="0 0 0" xyz="-0.2 -0.285 -0.1"/>
    <axis xyz="0 1 0"/>
    <limit effort="90" velocity="20"/>
  </joint>

  <link name="wheel_right_rear_link">
    <inertial>
      <mass value="5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0123" ixy="0" ixz="0" 
               iyy="0.0226" iyz="0" 
               izz="0.0123"/>
    </inertial>

    <collision name="wheel_right_rear_collision">
      <origin rpy="1.5707 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.0835"/>
      </geometry>
    </collision>

    <visual name="wheel_right_rear_visual">
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/Wheel.dae" scale="1.0 1.0 1.0"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>
  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://warebot_2020_description/meshes/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.19 -0.075 0.25" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://turtlebot3_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${asus_cam_rgb_px} ${asus_cam_rgb_py} ${asus_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${asus_cam_rgb_px} ${asus_cam_rgb_py + asus_cam_depth_offset} ${asus_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>
